# Generated by Django 5.2.14 on 2026-05-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Husayn', max_length=100)),
                ('role', models.CharField(default='Backend Developer', max_length=100)),
                ('description', models.TextField()),
                ('stack', models.CharField(default='Django • Python • JS', max_length=200)),
                ('country', models.CharField(default='Uzbekistan', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
