# Generated by Django 5.2.14 on 2026-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='years_experience',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
